### ISSUE TITLE
When directly logging in and jumping to the user chat interface, the historical chat data will not be pulled.

### ISSUE THREAD

**Issue by rudy-tao** [tinode/webapp#124]
**Describe the bug**
When directly logging in and jumping to the user chat interface, the historical chat data will not be pulled.

**To Reproduce**
1. Create a cred link on the server side. eg:http://localhost:6060/#cred/usrNPfP45f2imw?method=email&token=xxx&code=123456
2. Directly log in and redirect to the user chat interface.

**Expected behavior**
Display historical chat data.

**Comment by rudy-tao** [comment]
When backend automatically registers a user, it will generate a welcome message.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/webapp/commit/48405bcb945dcd5d6123671b8f62353c19ab9508. Please verify.

**Comment by rudy-tao** [comment]
> 
This did not fix the issue, historical messages still do not appear when opening the page.

**Comment by or-else** [comment]
Please attach a client-side log. Thanks.

**Comment by rudy-tao** [comment]
> 

![image](https://user-images.githubusercontent.com/40810931/234159216-c121a127-4ce0-43cd-8215-9430fc4d9e9f.png)

**Comment by rudy-tao** [comment]
@or-else

**Comment by or-else** [comment]
See the line in the log `"ver": "0.22.6"`? That means you are not using the fix. Please test the fix I provided.

**Comment by rudy-tao** [comment]
![image](https://user-images.githubusercontent.com/40810931/234160909-416d59e7-de36-4de9-a400-8e5085f824fd.png)

**Comment by rudy-tao** [comment]
@or-else This is the dev branch that I just pulled, compiled, and ran.

**Comment by rudy-tao** [comment]
![image](https://user-images.githubusercontent.com/40810931/234161651-4adfe6db-0204-4a93-9b64-731d253531a2.png)

**Comment by rudy-tao** [comment]
@or-else sorry, this is the log compiled and run using the next branch, and there are still no previous messages.

**Comment by or-else** [comment]
This should fix it: https://github.com/tinode/webapp/commit/5d56c1712846b3609e087bc6e06eb7fd91e763fc
Thanks.

**Comment by or-else** [comment]
@rudy-tao Have you had a chance to test the fix?

**Comment by rudy-tao** [comment]
![image](https://user-images.githubusercontent.com/40810931/234747802-a9c7d96b-0003-44a7-aec1-2e7edb41e3af.png)

**Comment by rudy-tao** [comment]
@or-else I tried to run it, but there was no display of the chat history data.

**Comment by rudy-tao** [comment]
I also found a problem that when using automatic login redirect links on mobile with different resolutions, it does not follow the login process.
I tried to debug the code and found that the SidepanelView in tinode-web.jsx was not rendering, which caused automatic login to fail.

**Comment by rudy-tao** [comment]
> @rudy-tao Have you had a chance to test the fix?

I added the following judgment in version 0.22.6, which solved my problem.

```js
if (this.state.isReader && !prevState.isReader){
      // If reader status has changed and data became available.
      // topic.getMeta(topic.startMetaQuery().withLaterData(MESSAGES_PAGE).build());
      this.subscribe(topic);
}
```

**Comment by or-else** [comment]
> I also found a problem that when using automatic login redirect links on mobile with different resolutions, it does not follow the login process. I tried to debug the code and found that the SidepanelView in tinode-web.jsx was not rendering, which caused automatic login to fail.

I'm confused. Are you describing a different problem?

**Comment by or-else** [comment]
I think I understand now why it's not working for you. You are trying to automatically subscribe user to a new P2P topic, one that he has not been subscribed to before.  That's actually a feature. Let me make it optional.

**Comment by rudy-tao** [comment]
> I added this feature: [08bdc7b](https://github.com/tinode/webapp/commit/08bdc7bc08b54984b4acaf8aa981bab63667f2fe) Change
> 
> https://github.com/tinode/webapp/blob/08bdc7bc08b54984b4acaf8aa981bab63667f2fe/src/config.js#L128
> 
> to `true` and recompile. It should work.

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/40810931/235119033-8a3f4ef1-d905-46dc-8469-3357f4e2fc2b.png">

**Comment by rudy-tao** [comment]
Still no history messages displayed...

**Comment by rudy-tao** [comment]
> I added this feature: [08bdc7b](https://github.com/tinode/webapp/commit/08bdc7bc08b54984b4acaf8aa981bab63667f2fe) Change
> 
> https://github.com/tinode/webapp/blob/08bdc7bc08b54984b4acaf8aa981bab63667f2fe/src/config.js#L128
> 
> to `true` and recompile. It should work.

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/40810931/235120241-cfb05e13-2756-4d97-894b-56578de2546a.png">

**Comment by or-else** [comment]
It works now https://github.com/tinode/webapp/commit/3689b5d52794becf96049081b050cb1c23dce7e3.
