### ISSUE TITLE
After building the app all texts are marked as !![OBSOLETE]!! or disappear

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/webapp#62]
Webapp version: 0.16.10
Tinode-sdk version: 0.16.10

I have updated npm.
After building the app, all spanish, russian, etc texts in` /src/i18n forlder` files are marked as `!![OBSOLETE]!!,` for example:
  `"validate_credential_action": ":!![OBSOLETE]!!:confirmar",`

Texts are being deleted from `/src/i18n/en.js` file and after building contains only this line:
`{}`

After building there are no texts in `/src/messages.json` file. Only:

```
{
  "en": {},
  "es": {},
  "ru": {}
...
}
```

**Comment by or-else** [comment]
Yes, the dependencies were recently updated, including a major Babel update. Babel required config changes. If you are using a custom `.babelrc`, please update it too or roll back the babel version.

**Comment by sanmiguel2019** [comment]
I don´t use custom .babelrc but this:
{
  "presets": ["@babel/preset-react", "@babel/preset-env"],
  "comments": false,
}


package.json:

**Comment by or-else** [comment]
He is the change in build which probably affected you:
https://github.com/tinode/webapp/commit/924459f84bd10944043877a1f1e8b5315411042b

See what is different in your build. `webpack.config.js` has changed a lot.

**Comment by or-else** [comment]
See if the translations are not being generated or not being copied: check if `webapp/src/i18n/` has valid language files, like `de.json`, `en.json` etc. If they are present and non-empty, then your build is just not copying them to the deployment file. The copy script is at `webapp/scripts/flatten-messages.js`.

**Comment by sanmiguel2019** [comment]
**Windows 7**
- Uninstalled nodejs. Installed nodejs.
- Downloaded [the most recent version](https://github.com/tinode/webapp) of Tinode´s webapp
- I ran the comand `npm install `in the apps folder. All modules were installed successfuly
- I ran the command `npm run vers && npm run build:prod && npm run build:dev && npm run build:css && npm run build:i18n`
- App builded successfully.

**Windows 10**
- Uninstalled Installed nodejs.
- Downloaded [the most recent version](https://github.com/tinode/webapp) of Tinode´s webapp
- I ran the comand `npm install `in the apps folder. All modules were installed successfuly
- I ran the command `npm run vers && npm run build:prod && npm run build:dev && npm run build:css && npm run build:i18n`
- App builded successfully 

**On both Windows 7 and Windows 10** 

appears only one warning in red:
`./src/index.js + 71 modules 296 KiB **[not cacheable]** [built] [code generated]`

After building the app, file `/src/i18n/en.json` becomes empty. After building it contains only: 
`{}`

After building all the texts of other language files in `/src/i18n/` folder get comment `!![OBSOLETE]!!`

```
{
  "validate_credential_action": ":!![OBSOLETE]!!:confirmar",
  "title_tag_manager": ":!![OBSOLETE]!!:Etiquetas (descubrimiento de usuarios)",
  "label_user_contacts": ":!![OBSOLETE]!!:Contactos:",
  "button_add_another": ":!![OBSOLETE]!!:Añadir contacto",
...
}
```

After building the file /erc/messages.json becomes empty. It contains only: 

```
{
"de": {},
"en": {},
"es": {},
"ko": {},
"ru": {},
"zh": {}
}
```

**Comment by or-else** [comment]
I can reproduce the problem. It looks like the formatjs is incorrectly configured. I'll update the issue as soon as I find the fix.

**Comment by or-else** [comment]
I believe this is fixed: https://github.com/tinode/webapp/commit/1172adefb49b41cf80c2f6ecbab30a3a059eab22
Please check. Thanks!

**Comment by sanmiguel2019** [comment]
Installed devel version with changes you have made but there is the same problem. After building texts from en.json and messages.json files disappear and all texts of other languages in the foldes/src/i18n are marked with !![OBSOLETE]!!

**Comment by or-else** [comment]
I found the problem, but it takes a lot of refactoring.

**Comment by or-else** [comment]
Please try `devel` again.

**Comment by sanmiguel2019** [comment]
Exactly the same problem. English language texts disappear. All the texts of other languages are marked with OBSOLETE. Also file /src/i18n/ex/base-en.json after building becomes empty.

**Comment by sanmiguel2019** [comment]
When I try to access options of the topic (by clicking on 3 dots on the right top corner of a topic or on the conversations list)

 
![3dots](https://user-images.githubusercontent.com/54183931/106277127-77a22780-6230-11eb-862f-2e9a0bb77f88.png)

appears this error:

```
Error: [@formatjs/intl] An `id` must be provided to format a message.
    at f (react-intl.umd.min.js:15)
    at be (react-intl.umd.min.js:15)
    at zt (react-intl.umd.min.js:23)
    at new S (context-menu.jsx:247)
    at fh (react-dom.production.min.js:81)
    at Ch (react-dom.production.min.js:114)
    at Pj (react-dom.production.min.js:233)
    at di (react-dom.production.min.js:168)
    at Nj (react-dom.production.min.js:168)
    at sc (react-dom.production.min.js:168)
Ye @ react-dom.production.min.js:141
Mh.c.callback @ react-dom.production.min.js:141
dh @ react-dom.production.min.js:80
Bj @ react-dom.production.min.js:145
Qj @ react-dom.production.min.js:176
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
eb @ react-dom.production.min.js:170
gf @ react-dom.production.min.js:162
(anonymous) @ react-dom.production.min.js:73
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
$g @ react-dom.production.min.js:73
ja @ react-dom.production.min.js:73
vk.Events.current @ react-dom.production.min.js:240
Ki @ react-dom.production.min.js:44
react-dom.production.min.js:73 Uncaught Error: [@formatjs/intl] An `id` must be provided to format a message.
    at f (react-intl.umd.min.js:15)
    at be (react-intl.umd.min.js:15)
    at zt (react-intl.umd.min.js:23)
    at new S (context-menu.jsx:247)
    at fh (react-dom.production.min.js:81)
    at Ch (react-dom.production.min.js:114)
    at Pj (react-dom.production.min.js:233)
    at di (react-dom.production.min.js:168)
    at Nj (react-dom.production.min.js:168)
    at sc (react-dom.production.min.js:168)
f @ react-intl.umd.min.js:15
be @ react-intl.umd.min.js:15
zt @ react-intl.umd.min.js:23
S @ context-menu.jsx:247
fh @ react-dom.production.min.js:81
Ch @ react-dom.production.min.js:114
Pj @ react-dom.production.min.js:233
di @ react-dom.production.min.js:168
Nj @ react-dom.production.min.js:168
sc @ react-dom.production.min.js:168
gf @ react-dom.production.min.js:162
(anonymous) @ react-dom.production.min.js:73
unstable_runWithPriority @ react.production.min.js:24
Za @ react-dom.production.min.js:73
$g @ react-dom.production.min.js:73
ja @ react-dom.production.min.js:73
vk.Events.current @ react-dom.production.min.js:240
Ki @ react-dom.production.min.js:44
```

**Comment by or-else** [comment]
> Exactly the same problem

I cannot reproduce. The `/src/i18n/ex/base-en.json` is correctly recreated even if deleted, messages correctly packed. Given that you have been able to run the app to get the error 
below, I suppose you have solved the problem.

> Error: [@formatjs/intl] An `id` must be provided to format a message.

Fixed in https://github.com/tinode/webapp/commit/fb5447c92f90bd39ae1842046e9c1c5cb0d0038d

**Comment by sanmiguel2019** [comment]
I don´t know that to do, the problem still persists. Downloaded and installed the latest `devel` again but still the same. 
The problem with `Error: [@formatjs/intl] An `id` must be provided to format a message.` is fixed now but after bulding still disappear english texts from all files and all the texts of other languages are marked as `OBSOLETE`.

`index.prod.js` file after building does not contain any texts but this: 
`... n=ReactIntl,o=JSON.parse('{"de":{},"en":{},"es":{},"ko":{},"ro":{},"ru":{},"zh":{}}'),l=firebase,r=(firebase.messaging,Tinode), ...`

Even English texts in some places of the app don´t not appear:
![account_settings](https://user-images.githubusercontent.com/54183931/106354586-d62bdc00-62ea-11eb-87b7-4b01754415b0.png)

**Comment by or-else** [comment]
I just double checked, everything worked as expected. The `base-en.json` and `messages.json` were successfully re-created after being deleted,  `index.prod.js` contained the translations: `n=ReactIntl,o=JSON.parse('{"de":{"validate_credential_action":"bestät...`

You did manage to build it correctly before: you've got `Error: [@formatjs/intl] An id must be provided to format a message.` when opening the menu. It means the build was successful, strings were present in the build. 

Please try to help me with debugging this issue as I no longer able to reproduce the problem. 

What is your system? (Mac, Windows, Linux)?
Do you see a valid `base-en.json` after running `npm run build`?
Do you see a valid `messages.json` after running `npm run build`?
Is your build process modified from the stock build in any way?

**Comment by sanmiguel2019** [comment]
**What is your system? (Mac, Windows, Linux)?**

Windows 7.  I also tried on Windows 10 (not the latest `devel `version but before you made changes) and the problem also persisted on Windows 10.

**Do you see a valid `base-en.json` after running npm run build?**
I see `base-en.json` after running npm run build but it's empty. It contains only 2 curly brackets:
```
{
}
```
Before building `base-en.json` file was not empty.

**Do you see a valid messages.json after running npm run build?**

Yes, I see a valid `messages.json` file after running npm run build but it's empty. It contains only this:
```
{
"de": {},
"en": {},
"es": {},
"ko": {},
"ru": {},
"zh": {}
}
```

Before building this file was not empty.

**Is your build process modified from the stock build in any way?**

Its not modified. 
Yes, I have my own modified version of the webapp (changed colors, removed some functions as registration, password recovery as I use rest authentication) but I see the problem also in the original version. 

Today I downloaded and installed the latest devel version and after building all texts from `base-en.json` , `messages.json` and `en.json` files disappear but all the texts of another languages in `/src/i18n` folder are marked with `OBSOLETE`. 

**This is my build log:**

```
C:\1\ws\tinode\chat>npm run vers && npm run build:css && npm run extract && npm run build:i18n && npm run build:prod && npm run build:dev

> Chat@0.16.10 vers C:\1\ws\tinode\chat
> node scripts/gen-version.js


> Chat@0.16.10 build:css C:\1\ws\tinode\chat
> postcss css/base.css > css/base.min.css


> Chat@0.16.10 extract C:\1\ws\tinode\chat
> formatjs extract 'src/**/*.jsx' --out-file src/i18n/ex/base-en.json --id-inter
polation-pattern '[sha512:contenthash:base64:6]'


> Chat@0.16.10 build:i18n C:\1\ws\tinode\chat
> node scripts/pack-messages.js


> Chat@0.16.10 build:prod C:\1\ws\tinode\chat
> webpack --mode production

asset index.prod.js 137 KiB [emitted] [minimized] (name: index) 1 related asset
asset tinode.prod.js 59.6 KiB [compared for emit] [from: node_modules/tinode-sdk
/umd/tinode.prod.js] [copied] [minimized]
orphan modules 228 KiB [orphan] 63 modules
runtime modules 718 bytes 3 modules
./src/index.js + 63 modules 228 KiB [not cacheable] [built] [code generated]
webpack 5.13.0 compiled successfully in 38933 ms

> Chat@0.16.10 build:dev C:\1\ws\tinode\chat
> webpack --mode development

asset tinode.dev.js 557 KiB [compared for emit] [from: node_modules/tinode-sdk/u
md/tinode.dev.js] [copied] [big]
asset index.dev.js 332 KiB [emitted] [big] (name: index) 1 related asset
runtime modules 997 bytes 4 modules
cacheable modules 228 KiB
  modules by path ./src/widgets/*.jsx 89.6 KiB 36 modules
  modules by path ./src/views/*.jsx 124 KiB 12 modules
  modules by path ./src/lib/*.js 12 KiB 6 modules
  modules by path ./src/*.js 2.22 KiB 3 modules
  ./src/messages.json 43 bytes [built] [code generated]
external "React" 42 bytes [built] [code generated]
external "ReactDOM" 42 bytes [built] [code generated]
external "ReactIntl" 42 bytes [built] [code generated]
external "firebase" 42 bytes [built] [code generated]
external ["firebase","messaging"] 42 bytes [built] [code generated]
external "Tinode" 42 bytes [built] [code generated]
webpack 5.13.0 compiled successfully in 26315 ms

C:\1\ws\tinode\chat>

```

**Comment by or-else** [comment]
> I see base-en.json after running npm run build but it's empty. 

OK, this is the core problem, everything else is the consequence.

This is the step where it happens:
```
> Chat@0.16.10 extract C:\1\ws\tinode\chat
> formatjs extract 'src/**/*.jsx' --out-file src/i18n/ex/base-en.json --id-interpolation-pattern '[sha512:contenthash:base64:6]'
```

I suspect the problem could be with the path, e.g. `/` vs `\` or something like this https://github.com/formatjs/formatjs-old/issues/383. I have no access to windows, maybe you can help debugging it.
Please add something like `"extract-test": "formatjs extract"` to `scripts section of your `package.json` file and see if you can get extraction to work by running the command manually, like
```
npm run extract-test -- 'src/**/*.jsx' --out-file src/i18n/ex/base-en.json --id-interpolation-pattern '[sha512:contenthash:base64:6]'
```
Put quotes around paths, change / to \ etc. The result of this call should be a non-empty `base-en.json`.
See more info here: https://formatjs.io/docs/getting-started/message-extraction

**Comment by sanmiguel2019** [comment]
Looks that this problem is not only with Tinode.
There is a [post](https://stackoverflow.com/questions/65156419/no-messages-returned-when-running-formatjs-extract-on-project-any-ideas-of-why) on Stackoverflow published on December 20. Unfortunately, no answers.

**Comment by or-else** [comment]
It's a problem on Windows. 

Try changing the paths, adding or removing single or double quotes around parameters as I suggested in the previous message. Maybe try changing `.jsx` to `.{jsx}` or `.{jsx|abc}` as I saw some messages on SO that it maybe a problem.

**Comment by sanmiguel2019** [comment]
Yes, removing quotes fixes the problem. Thanks. Changed the line:

`"extract": "formatjs extract 'src/**/*.jsx' --out-file src/i18n/ex/base-en.json --id-interpolation-pattern '[sha512:contenthash:base64:6]'",`

to:

`"extract": "formatjs extract src/**/*.jsx --out-file src/i18n/ex/base-en.json --id-interpolation-pattern '[sha512:contenthash:base64:6]'",`

and the problem is gone.

**Comment by or-else** [comment]
Great, thanks. I also works fine on the Mac, I made it the default.
